### ISSUE TITLE
xla jit error

### ISSUE THREAD

**Issue by dibyendudas0708** [ROCmSoftwarePlatform/tensorflow#17]
I am using the latest version on a P47 cluster. rocm tensorflow built from source with xla enabled. 

### Describe the problem
Using XLA JIT gives the following error: { I am doing inference only using a frozen model ]

2018-03-23 01:44:58.449221: W tensorflow/core/framework/op_kernel.cc:1192] Not found: could not find registered platform with id: 0x0x7f4e203fe904
Traceback (most recent call last):
  File "inference.py", line 43, in <module>
    predictions = sess.run(output_tensor,{'input:0': batch})
  File "/home/prj47-rack-05/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/prj47-rack-05/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/prj47-rack-05/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/home/prj47-rack-05/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: could not find registered platform with id: 0x0x7f4e203fe904
         [[Node: cluster_0/_0/_1 = _XlaLaunch[Nresources=0, Targs=[DT_FLOAT], Tconstants=[], Tresults=[DT_FLOAT], function=cluster_0[_XlaCompiledKernel=true, _XlaNumConstantArgs=0, _XlaNumResourceArgs=0], _device="/job:localhost/replica:0/task:0/gpu:0"](_arg_input_0_0/_3)]]

### Source code / logs
...
config = tf.ConfigProto()
config.graph_options.optimizer_options.global_jit_level = 1
with tf.Session(config=config) as sess:
...

**Comment by 7SK** [comment]
Hi @dibyendudas0708 , please provide the source link for the model you are using so that I can reproduce it at my end as well.

**Comment by dibyendudas0708** [comment]
I have a .pb file which is not available online. If you send me a location I can upload there.

**Comment by dibyendudas0708** [comment]
Hi-

Any update ?

**Comment by 7SK** [comment]
Hi @dibyendudas0708 , thanks for reporting the issue. the reported issue is fixed but we haven't tested XLA much. So currently I working on fixing the next issue. Will update you as soon as it fixed completely.

**Comment by 7SK** [comment]
@dibyendudas0708 ,  I ran the application you provided, it is working now
Thanks
