### ISSUE TITLE
Crashing on this script

### ISSUE THREAD

**Issue by boxerab** [ROCmSoftwarePlatform/tensorflow#21]
https://github.com/aymericdamien/TensorFlow-Examples/blob/master/examples/3_NeuralNetworks/dcgan.py

Log output:

2018-03-23 20:50:28.080349: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929] DMA: 0 
2018-03-23 20:50:28.080353: I tensorflow/core/common_runtime/gpu/gpu_device.cc:939] 0:   Y 
2018-03-23 20:50:28.080358: I tensorflow/core/common_runtime/gpu/gpu_device.cc:997] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Device 67df, pci bus id: 0000:01:00.0)
2018-03-23 20:50:28.409651: I tensorflow/core/kernels/conv_ops.cc:670] running auto-tune for Convolve
2018-03-23 20:50:28.409827: I tensorflow/core/kernels/conv_grad_input_ops.cc:858] running auto-tune for Backward-Data

**Comment by whchung** [comment]
@boxerab from the log it seems to be crashing inside `MIOpen` trying to locate the correct kernel. But we definitely need more logs to diagnose with the following env vars:

```
MIOPEN_ENABLE_LOGGING=1
HIP_TRACE_API=2
HCC_SERIALIZE_KERNEL=3
```

**Comment by boxerab** [comment]
[dump.txt](https://github.com/ROCmSoftwarePlatform/tensorflow/files/1843911/dump.txt)

**Comment by boxerab** [comment]
Would you guys consider adding these TF examples to your unit tests ?

**Comment by Mandrewoid** [comment]
@boxerab  is it possible you are using code written for a TF 1.4+ version?

**Comment by boxerab** [comment]
@Mandrewoid yes this is possible. How can I check ?

**Comment by boxerab** [comment]
I am just learning TF, btw. Not sure how to differentiate between 1.3 and 1.4

**Comment by boxerab** [comment]
Nonetheless, it shouldn't crash.

**Comment by whchung** [comment]
From the log this issue seems to be related with #16.

**Comment by Chern2** [comment]
@whchung I find a problem. If I try to use matplotlib library to plot some result from tensorflow, tensorflow dies and no feedback appears in the terminal. Of course, everything is fine if I do not try to plot figures!

**Comment by boxerab** [comment]
Still happening with latest MI-Open release

**Comment by whchung** [comment]
@boxerab The new `MIOpen` 1.3 release wasn't aiming to fix the issue. Current investigation shows for some reason C++ exception raised inside `MIOpen` went un-caught and aborts the whole TensorFlow, while within `MIOpen` implementation all exceptions are defined to be caught in top-level API. It could be a bug in `libunwind` and we are still looking into it.

**Comment by boxerab** [comment]
Cool, thanks for the update.

**Comment by whchung** [comment]
+ @bensander @scchan @pfultz2 @dagamayank for awareness.

The root cause has been figured out. Multiple instances of `libunwind` are loaded at runtime and messed up the exception handling routine. Need to disable `libunwind` dependency across various components within ROCm stack.

**Comment by boxerab** [comment]
Awesome. Thanks for fixing this.

**Comment by boxerab** [comment]
Great, ETA for 1.7.2 ?

**Comment by whchung** [comment]
Within this week. This is the last changeset be on the train.

**Comment by boxerab** [comment]
Cool. Thanks for letting me know.

**Comment by briansp2020** [comment]
@whchung Do you plan to fix https://github.com/ROCmSoftwarePlatform/tensorflow/issues/38#issuecomment-379806604 for ROCm 1.7.2 or is that TF only issue that can be fixed later?

I plan on participating http://xviewdataset.org/ challenge next. I used 1080 with 8GB of graphics memory for the Kaggle data science competition but I'm running into memory limit. So, if TF1.7+ is well supported on Vega FE, I'd like to try it for the next competition. TF object detection API seems to require TF 1.4 or higher...

**Comment by whchung** [comment]
@briansp2020 Normally I want to make PIP whl packages be as independent from ROCm release as possible.

Right now in #38 we know `concat` op is somehow incorrect.

If it's a host side issue then it's completely within TensorFlow and we just need to update the whl packages and that can be done independent of ROCm 1.7.2 release.

If it's a GPU kernel/compiler issue, we can still update the whl packages by temporarily forcing `concat` op only workable on CPU. We definitely would lose some perf but at least models / apps would be functional. And once the fix in the compiler is in the next ROCm release we can then turn them back onto GPU.

For TF 1.7+, I'll start posting some stuffs online very soon. Please keep an eye on this repository (and the changes of it).

**Comment by 7SK** [comment]
Hi @boxerab 
ROCm1.7.2 is released, with it the issue is resolved. Please give it a try.

**Comment by boxerab** [comment]
Yes, thanks, it no longer crashes.
However, every few times I run it, I get this exception thrown:

       terminate called after throwing an instance of 'miopen::Exception'
          what():  /data/repo/MIOpen/src/mlo_dir_conv.cpp:105: No solution found

**Comment by boxerab** [comment]
Here is the output with logging turned on:

MIOpen(HIP): miopenStatus_t miopenSet4dTensorDescriptor(miopenTensorDescriptor_t, miopenDataType_t, int, int, int, int){
tensorDesc = 
dataType = 1
n = 32
c = 1
h = 28
w = 28
}
MIOpen(HIP): miopenStatus_t miopenCreateTensorDescriptor(miopenTensorDescriptor_t *){
tensorDesc = 0
}
MIOpen(HIP): miopenStatus_t miopenSet4dTensorDescriptor(miopenTensorDescriptor_t, miopenDataType_t, int, int, int, int){
tensorDesc = 
dataType = 1
n = 32
c = 64
h = 24
w = 24
}
MIOpen(HIP): miopenStatus_t miopenCreateTensorDescriptor(miopenTensorDescriptor_t *){
tensorDesc = 0
}
MIOpen(HIP): miopenStatus_t miopenSet4dTensorDescriptor(miopenTensorDescriptor_t, miopenDataType_t, int, int, int, int){
tensorDesc = 
dataType = 1
n = 64
c = 1
h = 5
w = 5
}
MIOpen(HIP): miopenStatus_t miopenCreateConvolutionDescriptor(miopenConvolutionDescriptor_t *){
convDesc = 0[32m<<hip-api tid:4.9 4.9 hipLaunchKernel '_ZN5Eigen8internal15EigenMetaKernelINS_15TensorEvaluatorIKNS_14TensorAssignOpINS_9TensorMapINS_6TensorIiLi1ELi1EiEELi16ENS_11MakePointerEEEKNS_20TensorCwiseNullaryOpINS0_18scalar_constant_opIiEEKS8_EEEENS_9GpuDeviceEEEiEEvT_T0_' gridDim:{1024,1,1} groupDim:{1024,1,1} sharedMem:+0 stream:0.1 @2865031467779[0m

}
MIOpen(HIP): miopenStatus_t miopenInitConvolutionDescriptor(miopenConvolutionDescriptor_t, miopenConvolutionMode_t, int, int, int, int, int, int){
convDesc = 0, 0, 1, 1, 1, 1, 
c_mode = 0
pad_h = 0
pad_w = 0
u = 1
v = 1[32m<<hip-api tid:3.83 3.83 hipLaunchKernel '_ZN10tensorflow14BiasNHWCKernelIfEEviPKT_S3_PS1_i' gridDim:{32768,1,1} groupDim:{1024,1,1} sharedMem:+0 stream:0.1 @2865031508271[0m

dilation_h = 1
dilation_w = 1
}
MIOpen(HIP): miopenStatus_t miopenConvolutionForwardGetWorkSpaceSize(miopenHandle_t, const miopenTensorDescriptor_t, const miopenTensorDescriptor_t, const miopenConvolutionDescriptor_t, const miopenTensorDescriptor_t, size_t *){
wDesc = 64, 1, 5, 5
yDesc = 32, 64, 24, 24
convDesc = 0, 0, 1, 1, 1, 1, 
workSpaceSize = 139710619198447
}
[32m<<hip-api tid:3.84 3.84 hipLaunchKernel '_ZN5Eigen8internal15EigenMetaKernelINS_15TensorEvaluatorIKNS_14TensorAssignOpINS_9TensorMapINS_6TensorIfLi1ELi1EiEELi16ENS_11MakePointerEEEKNS_18TensorCwiseUnaryOpINS0_14scalar_tanh_opIfEEKNS4_INS5_IKfLi1ELi1EiEELi16ES7_EEEEEENS_9GpuDeviceEEEiEEvT_T0_' gridDim:{81920,1,1} groupDim:{1024,1,1} sharedMem:+0 stream:0.1 @2865031560731[0m
MIOpen(HIP): miopenStatus_t miopenFindConvolutionForwardAlgorithm(miopenHandle_t, const miopenTensorDescriptor_t, const void *, const miopenTensorDescriptor_t, const void *, const miopenConvolutionDescriptor_t, const miopenTensorDescriptor_t, void *, const int, int *, miopenConvAlgoPerf_t *, void *, size_t, bool){
xDesc = 32, 1, 28, 28
x = 0x509a63600
wDesc = 64, 1, 5, 5
w = 0x50a3aab00
convDesc = 0, 0, 1, 1, 1, 1, 
yDesc = 32, 64, 24, 24
y = 0x50c8dc600
requestAlgoCount = 1
returnedAlgoCount = -75642251
perfResults = 
workSpace = 0x509a82200
workSpaceSize = 57600
exhaustiveSearch = 0
}
[32m<<hip-api tid:3.85 3.85 hipLaunchKernel '_ZN10tensorflow7functor33SwapDimension0And2InTensor3SimpleIfEEviPKT_NS0_9DimensionILi3EEEPS2_' gridDim:{32768,1,1} groupDim:{1024,1,1} sharedMem:+0 stream:0.1 @2865031671876[0m
[32m<<hip-api tid:3.86 3.86 hipLaunchKernel '_ZN10tensorflow7functor37SwapDimension1And2InTensor3UsingTilesIfLi32ELi8EEEvPKT_NS0_9DimensionILi3EEEPS2_' gridDim:{8192,8,1} groupDim:{32,8,1} sharedMem:+0 stream:0.1 @2865031744816[0m
2018-04-30 19:37:31.822785: I tensorflow/core/kernels/conv_grad_input_ops.cc:858] running auto-tune for Backward-Data
[32m<<hip-api tid:5.36 5.36 hipLaunchKernel 'Im2Col' gridDim:{768,1,1} groupDim:{256,1,1} sharedMem:+0 stream:0.1 @2865034591990[0m
[32m<<hip-api tid:5.55 5.55 hipLaunchKernel 'miog_betac_alphaab' gridDim:{18432,1,1} groupDim:{64,1,1} sharedMem:+0 stream:0.1 @2865222876022[0m
MIOpen(HIP): Info2 [AmdgcnAssemble4BugDetection] /opt/rocm/opencl/bin/x86_64/clang  -x assembler -target amdgcn--amdhsa -mcpu=gfx900 /tmp/6e25-edf6-e68d-3e1f 2>&1
MIOpen(HIP): Info [DetectAmdRocmMetadataVersion] AMDHSA_1_0
terminate called after throwing an instance of 'miopen::Exception'
  what():  /data/repo/MIOpen/src/mlo_dir_conv.cpp:105: No solution found

**Comment by whchung** [comment]
@boxerab Please try the followings:

1) make sure we are using ROCm 1.7.2:

    apt show rocm-dkms

    should give us 1.7.148

2) make sure we are using TensorFlow PIP package built for ROCm 1.7.2:

$ md5sum tensorflow-1.3.0-cp35-cp35m-linux_x86_64.whl 
f189b887952647db07a7458ea550ca20  tensorflow-1.3.0-cp35-cp35m-linux_x86_64.whl

$ md5sum tensorflow-1.3.0-cp27-cp27mu-linux_x86_64.whl  
70c497565f69f0a046ba7ebf80d9d5ee  tensorflow-1.3.0-cp27-cp27mu-linux_x86_64.whl

   The packages are located at : http://repo.radeon.com/rocm/misc/tensorflow/ . The initial versions for ROCm 1.7.2 were uploaded last Saturday (4/28) and some users found we built it with AVX512 instructions 
 which aren't available in earlier Intel machines ( #51 ) so we revised the packages. Please kindly help download them and check against MD5 checksum above. 

3) make sure MIOpen kernel caches are wiped out:

    rm -rf ~/.cache/miopen

   Between ROCm releases OpenCL compiler used to build MIOpen kernels could be different and wiping out MIOpen kernel cache would ensure we always start from a clean slate.

**Comment by boxerab** [comment]
OK, did all that. I am now getting this error:


[32m<<hip-api tid:7.5206 7.5206 hipLaunchKernel '_ZN10tensorflow7functor37SwapDimension1And2InTensor3UsingTilesIfLi32ELi8EEEvPKT_NS0_9DimensionILi3EEEPS2_' gridDim:{8192,8,1} groupDim:{32,8,1} sharedMem:+0 stream:0.1 @646595623624[0m
[32m<<hip-api tid:7.5207 7.5207 hipLaunchKernel '_ZN10tensorflow14BiasNHWCKernelIfEEviPKT_S3_PS1_i' gridDim:{32768,1,1} groupDim:{1024,1,1} sharedMem:+0 stream:0.1 @646595666379[0m
[32m<<hip-api tid:7.5208 7.5208 hipLaunchKernel '_ZN5Eigen8internal15EigenMetaKernelINS_15TensorEvaluatorIKNS_14TensorAssignOpINS_9TensorMapINS_6TensorIfLi1ELi1EiEELi16ENS_11MakePointerEEEKNS_18TensorCwiseUnaryOpINS0_14scalar_tanh_opIfEEKNS4_INS5_IKfLi1ELi1EiEELi16ES7_EEEEEENS_9GpuDeviceEEEiEEvT_T0_' gridDim:{81920,1,1} groupDim:{1024,1,1} sharedMem:+0 stream:0.1 @646595706578[0m
[32m<<hip-api tid:7.5209 7.5209 hipLaunchKernel '_ZN5Eigen8internal15EigenMetaKernelINS_15TensorEvaluatorIKNS_14TensorAssignOpINS_18TensorLayoutSwapOpINS_9TensorMapINS_6TensorIfLi4ELi1EiEELi16ENS_11MakePointerEEEEEKNS_17TensorReshapingOpIKNS_6DSizesIiLi4EEEKNS_17TensorReductionOpINS0_18AvgPoolMeanReducerIfEEKNS_9IndexListINS_10type2indexILl1EEEJNSJ_ILl2EEEEEEKNS_18TensorImagePatchOpILln1ELln1EKNS4_IKNS5_INS6_IKfLi4ELi1EiEELi16ES8_EEEEEES8_EEEEEENS_9GpuDeviceEEEiEEvT_T0_' gridDim:{65536,1,1} groupDim:{1024,1,1} sharedMem:+0 stream:0.1 @646595765208[0m
2018-05-03 15:38:57.173768: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: size 1 must be non-negative, not -1135640368
	 [[Node: Discriminator/Flatten/Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](Discriminator/average_pooling2d_2/AvgPool, Discriminator/Flatten/concat)]]
2018-05-03 15:38:57.173792: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: size 1 must be non-negative, not -1135640368
	 [[Node: Discriminator/Flatten/Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](Discriminator/average_pooling2d_2/AvgPool, Discriminator/Flatten/concat)]]
Traceback (most recent call last):
  File "/home/aaron/src/tf-examples/examples/3_NeuralNetworks/dcgan.py", line 149, in <module>
    feed_dict=feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: size 1 must be non-negative, not -1135640368
	 [[Node: Discriminator/Flatten/Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](Discriminator/average_pooling2d_2/AvgPool, Discriminator/Flatten/concat)]]
	 [[Node: Mean_1/_43 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_943_Mean_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op u'Discriminator/Flatten/Reshape', defined at:
  File "/home/aaron/src/tf-examples/examples/3_NeuralNetworks/dcgan.py", line 86, in <module>
    disc_real = discriminator(real_image_input)
  File "/home/aaron/src/tf-examples/examples/3_NeuralNetworks/dcgan.py", line 70, in discriminator
    x = tf.contrib.layers.flatten(x)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1446, in flatten
    outputs = array_ops.reshape(inputs, flat_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 2619, in reshape
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): size 1 must be non-negative, not -1135640368
	 [[Node: Discriminator/Flatten/Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](Discriminator/average_pooling2d_2/AvgPool, Discriminator/Flatten/concat)]]
	 [[Node: Mean_1/_43 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_943_Mean_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

**Comment by boxerab** [comment]
This is under python 2.7

**Comment by whchung** [comment]
/cc @sunway513 

@boxerab This is weird. We've never seen such errors before. Neither on Python2 or Python3.

@sunway513 will push out a public Docker container completely based on 1.7.2 so maybe you can try use it.

**Comment by boxerab** [comment]
Yes, so this happens when I have this environment variable `HIP_TRACE_API=2` set.
If I remove this, then no exception.

**Comment by boxerab** [comment]
And when I set `HCC_SERIALIZE_KERNEL=3`

**Comment by boxerab** [comment]
Also with `MIOPEN_ENABLE_LOGGING=1`

**Comment by boxerab** [comment]
So, crash happens when environment variables are set

**Comment by boxerab** [comment]
Also, if I run without env variables set, after a certain number of steps I get repeated `nan`
for loss:

`Step 2400: Generator Loss: nan, Discriminator Loss: nan`

**Comment by sunway513** [comment]
@boxerab , the updated docker image is ready:
rocm/hiptensorflow:rocm1.7.2

**Comment by whchung** [comment]
@boxerab I do suspect your ROCm or TensorFlow installation is somehow corrupted. Please first make sure `rocm-dkms` package installed in the bare metal is 1.7.148, and try the 1.7.2 container from @sunway513 above.

**Comment by boxerab** [comment]
Thanks. This script uses UI components like Tk, so can't run on docker.

**Comment by boxerab** [comment]
As for `rocm-dkms` :

Package: rocm-dkms
Version: 1.7.148
Priority: optional
Section: devel
Maintainer: Advanced Micro Devices Inc.
Installed-Size: 13.3 kB
Depends: rocm-dev, compute-firmware, rock-dkms
Homepage: https://github.com/RadeonOpenCompute/ROCm
Download-Size: 1,012 B
APT-Manual-Installed: yes
APT-Sources: http://repo.radeon.com/rocm/apt/debian xenial/main amd64 Packages
Description: Radeon Open Compute (ROCm) Runtime software stack
