### ISSUE TITLE
Race Condition while running MSSD detector

### ISSUE THREAD

**Issue by tadaoisgod** [ROCmSoftwarePlatform/tensorflow#24]
-----------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: 
- **TensorFlow version (use command below)**: [original URL from tutorial](http://repo.radeon.com/rocm/misc/tensorflow/tensorflow-1.3.0-cp35-cp35m-linux_x86_64.whl)
- **Python version**: 3.5.2
- **Bazel version (if compiling from source)**: Not compiling from source.
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: RX 480
- **Exact command to reproduce**: python inference_usbCam_face.py 0

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
Race condition happens randomly after running [yeepcho MSSD Face Detector](https://github.com/yeephycho/tensorflow-face-detection) for a while. Program starts and detects faces in a webcam input. After a random amount of time, the following error happens:

 `tensorflow.python.framework.errors_impl.InvalidArgumentError: WhereOp: Race condition between counting the number of true elements and writing them.  When counting, saw 5343 elements; but when writing their indices, saw 4691 elements.`

Error does not occur in original Tensorflow 1.3, 1.4, 1.5.

### Source code / logs

```
$ python inference_usbCam_face.py 0
2018-03-27 15:55:40.977879: W tensorflow/stream_executor/rocm/rocm_driver.cc:405] creating context when one is currently active; existing: 0x7fef3a1d6e60
2018-03-27 15:55:40.978016: I tensorflow/core/common_runtime/gpu/gpu_device.cc:907] Found device 0 with properties: 
name: Device 67df
AMDGPU ISA: gfx803
memoryClockRate (GHz) 1.288
pciBusID 0000:09:00.0
Total memory: 8.00GiB
Free memory: 7.75GiB
2018-03-27 15:55:40.978031: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929] DMA: 0 
2018-03-27 15:55:40.978037: I tensorflow/core/common_runtime/gpu/gpu_device.cc:939] 0:   Y 
2018-03-27 15:55:40.978054: I tensorflow/core/common_runtime/gpu/gpu_device.cc:997] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Device 67df, pci bus id: 0000:09:00.0)
480 640
2018-03-27 15:55:42.636644: I tensorflow/core/kernels/conv_ops.cc:670] running auto-tune for Convolve
2018-03-27 15:55:46.599926: I tensorflow/core/kernels/conv_ops.cc:670] running auto-tune for Convolve
2018-03-27 15:55:48.923635: I tensorflow/core/kernels/conv_ops.cc:670] running auto-tune for Convolve
2018-03-27 15:55:50.625544: I tensorflow/core/kernels/conv_ops.cc:670] running auto-tune for Convolve
2018-03-27 15:55:52.611701: I tensorflow/core/kernels/conv_ops.cc:670] running auto-tune for Convolve
inference time cost: 12.132970094680786
480 640
inference time cost: 0.034346818923950195
480 640
inference time cost: 0.03496980667114258
480 640
inference time cost: 0.031478166580200195
480 640
inference time cost: 0.034105777740478516

...
...
...

inference time cost: 0.032404184341430664
480 640
inference time cost: 0.039130449295043945
480 640
inference time cost: 0.03366279602050781
480 640
2018-03-27 16:02:07.797307: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: WhereOp: Race condition between counting the number of true elements and writing them.  When counting, saw 5343 elements; but when writing their indices, saw 4691 elements.
	 [[Node: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/FilterGreaterThan_1/Where = Where[_device="/job:localhost/replica:0/task:0/cpu:0"](Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/FilterGreaterThan_1/Greater/_153)]]
2018-03-27 16:02:07.797332: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: WhereOp: Race condition between counting the number of true elements and writing them.  When counting, saw 5343 elements; but when writing their indices, saw 4691 elements.
	 [[Node: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/FilterGreaterThan_1/Where = Where[_device="/job:localhost/replica:0/task:0/cpu:0"](Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/FilterGreaterThan_1/Greater/_153)]]
2018-03-27 16:02:07.797601: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: WhereOp: Race condition between counting the number of true elements and writing them.  When counting, saw 5343 elements; but when writing their indices, saw 4691 elements.
	 [[Node: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/FilterGreaterThan_1/Where = Where[_device="/job:localhost/replica:0/task:0/cpu:0"](Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/FilterGreaterThan_1/Greater/_153)]]
Traceback (most recent call last):
  File "/home/tadao/.virtualenvs/cv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/home/tadao/.virtualenvs/cv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1306, in _run_fn
    status, run_metadata)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/tadao/.virtualenvs/cv/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: WhereOp: Race condition between counting the number of true elements and writing them.  When counting, saw 5343 elements; but when writing their indices, saw 4691 elements.
	 [[Node: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/FilterGreaterThan_1/Where = Where[_device="/job:localhost/replica:0/task:0/cpu:0"](Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/FilterGreaterThan_1/Greater/_153)]]
	 [[Node: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/TensorArrayWrite_4/TensorArrayWriteV3/_205 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_2820_Postprocessor/BatchMultiClassNonMaxSuppression/map/while/TensorArrayWrite_4/TensorArrayWriteV3", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](^_cloopPostprocessor/BatchMultiClassNonMaxSuppression/map/while/stack_1/_6)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inference_usbCam_face.py", line 107, in <module>
    (boxes, scores, classes, num_detections) = tDetector.run(image)
  File "inference_usbCam_face.py", line 72, in run
    feed_dict={image_tensor: image_np_expanded})
  File "/home/tadao/.virtualenvs/cv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/tadao/.virtualenvs/cv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/tadao/.virtualenvs/cv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/home/tadao/.virtualenvs/cv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: WhereOp: Race condition between counting the number of true elements and writing them.  When counting, saw 5343 elements; but when writing their indices, saw 4691 elements.
	 [[Node: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/FilterGreaterThan_1/Where = Where[_device="/job:localhost/replica:0/task:0/cpu:0"](Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/FilterGreaterThan_1/Greater/_153)]]
	 [[Node: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/TensorArrayWrite_4/TensorArrayWriteV3/_205 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_2820_Postprocessor/BatchMultiClassNonMaxSuppression/map/while/TensorArrayWrite_4/TensorArrayWriteV3", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](^_cloopPostprocessor/BatchMultiClassNonMaxSuppression/map/while/stack_1/_6)]]

Caused by op 'Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/FilterGreaterThan_1/Where', defined at:
  File "inference_usbCam_face.py", line 94, in <module>
    tDetector = TensoflowFaceDector(PATH_TO_CKPT)
  File "inference_usbCam_face.py", line 38, in __init__
    tf.import_graph_def(od_graph_def, name='')
  File "/home/tadao/.virtualenvs/cv/lib/python3.5/site-packages/tensorflow/python/framework/importer.py", line 313, in import_graph_def
    op_def=op_def)
  File "/home/tadao/.virtualenvs/cv/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/tadao/.virtualenvs/cv/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): WhereOp: Race condition between counting the number of true elements and writing them.  When counting, saw 5343 elements; but when writing their indices, saw 4691 elements.
	 [[Node: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/FilterGreaterThan_1/Where = Where[_device="/job:localhost/replica:0/task:0/cpu:0"](Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/FilterGreaterThan_1/Greater/_153)]]
	 [[Node: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/TensorArrayWrite_4/TensorArrayWriteV3/_205 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_2820_Postprocessor/BatchMultiClassNonMaxSuppression/map/while/TensorArrayWrite_4/TensorArrayWriteV3", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](^_cloopPostprocessor/BatchMultiClassNonMaxSuppression/map/while/stack_1/_6)]]


```

**Comment by whchung** [comment]
@tadaoisgod I'm trying to reproduce the issue. My workstation doesn't come with a webcam so I'm using `inference_video_face.py` in the same repository. I fed it with some mp4 files but couldn't reproduce the issue yet.

I'd like to understand how long did you run into the issue with `WhereOp`? Currently I have to force `WhereOp` run on CPU ( logged at: https://github.com/ROCmSoftwarePlatform/tensorflow/blob/rocm-v1/rocm_docs/core_kernels.md ) due to certain unmet dependencies on ROCm platform.
