### ISSUE TITLE
Import error after a fresh installation (followed the basic installation steps)

### ISSUE THREAD

**Issue by xyang2013** [ROCmSoftwarePlatform/tensorflow#33]
Code
```
import tensorflow as tf

a_cpu = tf.Variable(0, name="a_cpu")
with tf.device('/gpu:0'):
    a_gpu = tf.Variable(0, name="a_gpu")

sess = tf.Session(config=tf.ConfigProto(allow_soft_placement=True, log_device_placement=True))
sess.run(tf.global_variables_initializer())
```

Error output
```
importError                               Traceback (most recent call last)
/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py in <module>()
     40     sys.setdlopenflags(_default_dlopen_flags | ctypes.RTLD_GLOBAL)
---> 41   from tensorflow.python.pywrap_tensorflow_internal import *
     42   from tensorflow.python.pywrap_tensorflow_internal import __version__

/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py in <module>()
     27             return _mod
---> 28     _pywrap_tensorflow_internal = swig_import_helper()
     29     del swig_import_helper

/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py in swig_import_helper()
     23             try:
---> 24                 _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
     25             finally:

/usr/lib/python3.5/imp.py in load_module(name, file, filename, details)
    241         else:
--> 242             return load_dynamic(name, filename, file)
    243     elif type_ == PKG_DIRECTORY:

/usr/lib/python3.5/imp.py in load_dynamic(name, path, file)
    341             name=name, loader=loader, origin=path)
--> 342         return _load(spec)
    343 

ImportError: libhipfft.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
~/repos/tensorflow_tutorials/caicloud/p252.py in <module>()
----> 1 import tensorflow as tf
      2 
      3 a_cpu = tf.Variable(0, name="a_cpu")
      4 with tf.device('/gpu:0'):
      5     a_gpu = tf.Variable(0, name="a_gpu")

/usr/local/lib/python3.5/dist-packages/tensorflow/__init__.py in <module>()
     22 
     23 # pylint: disable=wildcard-import
---> 24 from tensorflow.python import *
     25 # pylint: enable=wildcard-import
     26 

/usr/local/lib/python3.5/dist-packages/tensorflow/python/__init__.py in <module>()
     47 import numpy as np
     48 
---> 49 from tensorflow.python import pywrap_tensorflow
     50 
     51 # Protocol buffers

/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py in <module>()
     50 for some common reasons and solutions.  Include the entire stack trace
     51 above this error message when asking for help.""" % traceback.format_exc()
---> 52   raise ImportError(msg)
     53 
     54 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libhipfft.so: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by whchung** [comment]
@xyang2013 from the log it appears you are using an older version of whl package which still depends on `hipfft`. We have switched to use `rocfft` which ships along with official ROCm 1.7.1.

Could you show me the md5sum of the whl package you used?

**Comment by whchung** [comment]
@xyang2013 I've packaged the new whl in a clean environment and made sure the test you provided works fine:
https://www.dropbox.com/sh/udkismzspwi9bi1/AAAnjxdexEH4HiZtGeAMAz_fa?dl=0

We'll update the package on `repo.radeon.com` shortly after. + @jedwards-AMD for awareness.

**Comment by whchung** [comment]
Thanks @jedwards-AMD for revising the whl packages.

@xyang2013 please help validate the new whl package at http://repo.radeon.com/rocm/misc/tensorflow/tensorflow-1.3.0-cp35-cp35m-linux_x86_64.whl gets the issue resolved.

md5sum is:

```
bb6a4a1fb47d703c0b9844cbf7b8e7fd  tensorflow-1.3.0-cp35-cp35m-linux_x86_64.whl
```

**Comment by xyang2013** [comment]
@whchung Thank you. I am trying it right now. By the way, what is the best way to manage software updates? Like in this case, I was not sure what would be the best way to remove the Tensorflow installation and I decided to restart from scratch which is very time consuming. Given the port is in active development, could you please outline an appropriate approaches to manage updates and fixes? Thank you again.

**Comment by whchung** [comment]
@xyang2013 since we are only updating whl packages now, `pip3 uninstall -y tensorflow` and `pip3 install tensorflow-1.3.0-cp35-cp35m-linux_x86_64.whl` should do.

As this project is delivered in `.whl` format, not Ubuntu `.deb`  or RHEL/CentOS `.rpm`, so it does not follow standard ROCm release process where a more solid process is in place yet. We are working on improving the process and will share more information once it's available. For now checking md5sum of the whl package is the best way.

**Comment by xyang2013** [comment]
@whchung Thank you. I tried the new package and it worked for the above example.
