### ISSUE TITLE
DCGAN produces NaN during training

### ISSUE THREAD

**Issue by daniellowell** [ROCmSoftwarePlatform/tensorflow#48]
### System information
Running DCGAN from here:
https://github.com/carpedm20/DCGAN-tensorflow

Native OS:
16.04.1 with ROCm 1.71

Using Docker image to run the benchmark:
sunway513/hiptensorflow:tf13-rocm171-v1-nan-fixed-enhanced

GPU:
Vega10

To reproduce:

1. Clone the repo from above link into the docker.
2. cd into DCGAN directory
3. Run the command: `python3 download.py mnist celebA`
4. To train: `python3 main.py --dataset mnist --input_height=28 --output_height=28 --train`

Around the 4th epoch I'm seeing the NaN pop up.

Output:
```
Epoch: [ 4/25] [  15/1093] time: 341.9423, d_loss: 1.40019155, g_loss: 0.66751683
Epoch: [ 4/25] [  16/1093] time: 342.0152, d_loss: 1.39781117, g_loss: 0.67352808
Epoch: [ 4/25] [  17/1093] time: 342.0869, d_loss: 1.37966180, g_loss: 0.68313897
Epoch: [ 4/25] [  18/1093] time: 342.1604, d_loss: 1.38827240, g_loss: 0.68410325
Epoch: [ 4/25] [  19/1093] time: 342.2326, d_loss: 1.34625685, g_loss: 0.72638261
2018-04-19 16:24:45.566709: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Nan in summary histogram for: d_
	 [[Node: d_ = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](d_/tag, discriminator_1/Sigmoid/_233)]]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1306, in _run_fn
    status, run_metadata)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Nan in summary histogram for: d_
	 [[Node: d_ = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](d_/tag, discriminator_1/Sigmoid/_233)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 103, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 86, in main
    dcgan.train(FLAGS)
  File "/root/DCGAN-tensorflow/model.py", line 235, in train
    self.y:batch_labels,
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Nan in summary histogram for: d_
	 [[Node: d_ = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](d_/tag, discriminator_1/Sigmoid/_233)]]

Caused by op 'd_', defined at:
  File "main.py", line 103, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 65, in main
    data_dir=FLAGS.data_dir)
  File "/root/DCGAN-tensorflow/model.py", line 87, in __init__
    self.build_model()
  File "/root/DCGAN-tensorflow/model.py", line 115, in build_model
    self.d__sum = histogram_summary("d_", self.D_)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/summary/summary.py", line 192, in histogram
    tag=tag, values=values, name=scope)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_logging_ops.py", line 129, in _histogram_summary
    name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Nan in summary histogram for: d_
	 [[Node: d_ = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](d_/tag, discriminator_1/Sigmoid/_233)]]
```

**Comment by dagamayank** [comment]
@7SK According to our previous data this test was working fine.
http://confluence.amd.com/pages/viewpage.action?spaceKey=~sandkuma&title=Tensorflow+research+models

**Comment by 7SK** [comment]
Hi @dagamayank 
Yes, I was able to run it successfully earlier with both the datasets. Reverified it on one of the docker images I pushed earlier (sunway513/hiptensorflow:tf-rocm-0.2.1sk2), I was able to successfully train it with and without serializing the kernel( using HCC_SERIALIZE_KERNEL=0x3). 
Hi @daniellowell 
I tried to train it with docker sunway513/hiptensorflow:tf13-rocm171-v1-no-libunwind, I was able to run it successfully. You observed issue on both sunway513/hiptensorflow:tf13-rocm171-v1-no-libunwind and sunway513/hiptensorflow:tf13-rocm171-v1-nan-fixed-enhanced docker images. I did’t verified it on sunway513/hiptensorflow:tf13-rocm171-v1-nan-fixed-enhanced, hoping it will work with this as well.
It is not a bug in rocm port of tensorflow, but issue with loading the previous checkpoint. If somehow the training process is interrupted (maybe because of seg fault due to the libunwind or using ctrl+C ) and if we try to retrain it without cleaning checkpoint folder, it is generating nan value at random instance. I observed it earlier as well. Please retry training it after deleting checkpoint and logs folders, it should work.
I tried it on Polaris card with 28 compute units, I couldn’t try it on vega. Please reopen the issue if you still observe it, may be the issue is specific to vega only.

**Comment by daniellowell** [comment]
I don't think this issue is quite done.
You did not run the test on the hardware I produced the issue; i.e., Vega10.
Additionally, this statement does not match the issue:
"It is not a bug in rocm port of tensorflow, but issue with loading the previous checkpoint. "
I was able to reproduce the issue multiple times running the training from scratch without checkpointing. In fact when I reran with a checkpoint I was sometimes able to make progress by restarting multiple times.
I tried this on:
sunway513/hiptensorflow:tf13-rocm171-v1-no-libunwind
sunway513/hiptensorflow:tf13-rocm171-v1-nan-fixed-enhanced

Both had the same issue.

"Please reopen the issue if you still observe it, may be the issue is specific to vega only."
Doesn't think make it still an issue??

**Comment by 7SK** [comment]
@daniellowell Thanks for re-opening the issue

**Comment by whchung** [comment]
Relevant issue: https://github.com/carpedm20/DCGAN-tensorflow/issues/25 . Though not too much insights there.
